services:

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sandbox
    ports:
      - "5430:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"

  redis:
    image: redis:7
    ports:
      - "6399:6379"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile

    container_name: user-service

    ports:
      - "3093:3093"

    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379

    depends_on:
      - redis

volumes:
  grafana_data:
